language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="AndrewRingenbergs - CI"
    - GIT_EMAIL="AndrewRingenbergs@CI.com"
    - SOURCE_DIR="dist"
    - DEPLOY_BRANCH="master"
